---

- name: Get OpenZiti core version if latest is provided
  ansible.builtin.uri:
    url: "{{ openziti_core_metadata_url }}"
    body_format: json
  register: api_response_payload
  when: openziti_core_version == 'latest'

- name: Set OpenZiti core binaries binaries version if latest is provided
  vars:
    component_version: "{{ api_response_payload['json']['tag_name'] | \
      replace('v', '') }}"
  ansible.builtin.set_fact:
    openziti_core_version: "{{ component_version }}"
  when: openziti_core_version == "latest"

- name: Clone Openziti core repository on cache server
  ansible.builtin.git:
    repo: "{{ openziti_core_repository_url }}"
    dest: "{{ openziti_cache_core_sources_path }}"
    version: "v{{ openziti_core_version }}"
  delegate_to: "{{ openziti_cache_host }}"
  delegate_facts: false

- name: Copy configuration files on remote hosts
  ansible.builtin.copy:
    src: "{{ openziti_cache_config_path }}/{{ item }}"
    dest: "{{ openziti_remote_configuration_path }}"
  with_items: "{{ openziti_components | \
    map('extract', openziti_config_files) | \
    select('defined') }}"
