---

- name: Make sure tar is installed on Zac hosts
  ansible.builtin.package:
    name: tar
    state: present
  when: "'ziti-console' in openziti_components"
  become: true

- name: Make sure tar is installed on cache server
  ansible.builtin.package:
    name: tar
    state: present
  delegate_to: "{{ openziti_cache_host }}"
  delegate_facts: false
  become: true
  vars:
    ansible_become_pass: "lilou"

- name: Make sure git is installed on cache server
  ansible.builtin.package:
    name: git
    state: present
  delegate_to: "{{ openziti_cache_host }}"
  delegate_facts: false
  become: true
  vars:
    ansible_become_pass: "lilou"
