---

dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu_amd64
    image: docker.io/amd64/ubuntu
    pre_build_image: false
    groups:
      - ziti_controller
      - ziti_router
      - ziti_tunnel
      - ziti
      - ziti_console

  - name: oracle_amd64
    image: docker.io/amd64/oraclelinux:8
    pre_build_image: false
    groups:
      - ziti_controller
      - ziti_router
      - ziti_tunnel
      - ziti

provisioner:
  name: ansible
  inventory:
    host_vars:
      ubuntu_amd64:
        ansible_user: ansible
      oracle_amd64:
        ansible_user: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
