---

- name: Verify
  hosts: all
  vars_files:
    - ../../defaults/main.yaml
  tasks:
    - name: Verify that OpenZiti components are present on remote hosts
      ansible.builtin.stat:
        path: "{{ openziti_binaries_path_remote }}/{{ item }}"
      with_items: "{{ openziti_components }}" # yamllint disable-line rule:line-length rule:comments
