---
openziti_version: latest
openziti_supported_os_architecture: 
  linux:
    - arm64
    - arm
    - amd64
  windows:
    - amd64
  darwin:
    - amd64

openziti_cache_releases_dir: "/tmp/openziti_releases/{{ openziti_archive_name }}"
openziti_cache_downloads_dir: /tmp/openziti_downloads
openziti_cache_localhost: true
openziti_cache_host: "{% if openziti_cache_localhost %}localhost{% else %}{{ groups['cache_server'][0] }}{% endif %}"

openziti_os_architecture: "{{ ansible_architecture | replace('aarch', 'arm')}}"
openziti_os_name: "{{ ansible_system | lower }}"
openziti_archive_extension: "{{ 'zip' if ansible_system == 'Windows' else 'tar.gz'}}"

openziti_archive_name: "ziti-{{ openziti_os_name }}-{{ openziti_os_architecture}}-{{ openziti_version }}"
openziti_binaries_url: "https://github.com/openziti/ziti/releases/download/v{{ openziti_version }}/{{ openziti_archive_name }}.{{ openziti_archive_extension }}"

openziti_binaries_path_remote: /usr/local/bin
openziti_components:
  - ziti-controller
  - ziti-router
  - zidi-tunnel
  - ziti

