---

- name: Download OpenZiti binaries on cache server
  ansible.builtin.get_url:
    url: "{{ openziti_binaries_url }}"
    dest: "{{ openziti_cache_downloads_dir }}"
  delegate_to: "{{ openziti_cache_host }}"
  delegate_facts: false
  become: "{{ not openziti_cache_localhost }}"
  run_once: true

- name: Unarchive OpenZiti binaries on cache server
  ansible.builtin.unarchive:
    src: "{{ openziti_cache_downloads_dir }}/{{ openziti_archive_name }}.{{ openziti_archive_extension }}"
    dest: "{{ openziti_cache_release_version_dir }}"
    owner: "ares"
  delegate_to: "{{ openziti_cache_host }}"
  delegate_facts: false
  become: "{{ not openziti_cache_localhost }}"
  run_once: true

- name: Copy binaries from cache server to ansible controller
  ansible.builtin.fetch:
    src: "{{ openziti_cache_release_version_dir }}/{{ item }}"
    dest: "{{ openziti_cache_releases_dir }}/{{ item }}"
  with_items: "{{ openziti_components }}"
  when: not openziti_cache_localhost
  delegate_to: "localhost"
  delegate_facts: false
  become: "{{ not openziti_cache_localhost }}"
  run_once: true

