---
- name: Check remote OS and OS Architecture
  ansible.builtin.fail: 
    msg: "Unsupported OS or OS Architecture"
  when: 
    - openziti_os_name not in openziti_supported_os_architecture.keys()
    - openziti_os_architecture not in openziti_supported_os_architecture[openziti_os_name].values()

- name: Make sure required packages are installed
  import_tasks: required_packages.yml

- name: Set OpenZiti version facts
  import_tasks: set_openziti_versions.yml

- name: Create downloads and releases directories on cache server
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  delegate_to: "{{ openziti_cache_host }}"
  delegate_facts: false
  become: "{{ not openziti_cache_localhost }}"
  run_once: true
  loop:
    - "{{ openziti_cache_release_version_dir }}"
    - "{{ openziti_cache_downloads_dir }}"

- name: Download OpenZiti binaries to cache server
  import_tasks: download_binaries.yml

- name: Download OpenZiti console to cache server
  import_tasks: download_console.yml

- name: Copy binaries from ansible controller to remote host
  ansible.builtin.copy:
    src: "{{ openziti_cache_release_version_dir }}/ziti/{{ item }}"
    dest: "{{ openziti_binaries_path_remote }}/{{ item }}"
  become: true
  with_items: "{{ openziti_components | intersect(group_names | map('replace', '_', '-')) }}"








